import type {Metadata} from "next";
import {Work_Sans} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Providers from "@/app/providers";

const typeFont = Work_Sans({subsets: ["latin"], weight: ["400"]});

export const metadata: Metadata = {
  title: "Movies Libelula",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={typeFont.className}>
      <Header/>
      <Providers>{children}</Providers>
      </body>
      </html>
  );
}